version: '2'
services:
  dtserver:
    networks:
      - appmon_sandbox
    image: "dynatrace/server:6.5-slim"
    environment:
      DT_SERVER_NAME: "dtserver"
      #DT_SERVER_LICENSE_KEY_FILE_URL: "${DT_SERVER_LICENSE_KEY_FILE_URL}"
      HOST_NAME: "dtserver"
    expose:
      - "9910" #Web UI with http
    #volumes:
    #  - "/tmp/log/dynatrace/servers/dtserver:/dynatrace/log/server/dtserver"
    restart: always
  nginx:
    restart: always
    #build: ./nginx
    image: nginx
    depends_on:
        - dtserver
    volumes:
      - "./nginx/:/etc/nginx"
    networks:
      - appmon_sandbox
    ports: 
      - "8000:8000" # Test port
      - "2021:2021" # Dynatrace Clients (TCP with SSL)
      - "8023:8023" # Dynatrace Clients (HTTP Tunnel)
      - "8020:8020" # Dynatrace Web Server (HTTP)
      - "6699:6699" # Dynatrace Collector listening
      - "8021:8021" # Dynatrace Web Server (HTTPS)
      - "9911:9911" # Dynatrace Web UI (HTTPS)
      - "8023:8023" #
networks:
  appmon_sandbox:
