version: '2'
services:
  dtserver:
    networks:
      - appmon_sandbox
    image: "dynatrace/server:6.5-slim"
    environment:
      DT_SERVER_NAME: "dtserver"
      #DT_SERVER_LICENSE_KEY_FILE_URL: "${DT_SERVER_LICENSE_KEY_FILE_URL}"
      HOST_NAME: "docker-dtserver"
    #volumes:
    #  - "/tmp/log/dynatrace/servers/dtserver:/dynatrace/log/server/dtserver"
  nginx:
    #restart: always
    build: ./nginx
    depends_on:
        - dtserver
    #volumes:
    #  - "./nginx/:/etc/nginx"
    container_name: "appmon_lb"
    hostname: "appmon_lb"
    networks:
      - appmon_sandbox
    ports: 
      - "2020:2020" # Dynatrace Clients (TCP)
      - "2021:2021" # Dynatrace Clients (TCP with SSL)
      - "8020:8020" # Dynatrace Web Server (HTTP)
      - "8021:8021" # Dynatrace Web Server (HTTPS)
      - "9911:9911" # Dynatrace Web UI (HTTPS)
      #- "9998:9998" # Dynatrace Agents (TCP)
networks:
  appmon_sandbox:
