# Set nginx base image
FROM nginx

# File Author / Maintainer

# Copy custom configuration file from the current directory
COPY nginx.conf /etc/nginx/nginx.conf
#COPY sites-available.conf /etc/nginx/sites-available/default
